// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4YlGe9P3Mb57hENC2l6eJnSpY0Xy-BzM',
    appId: '1:363285191898:web:1d75ea8469d01498e499e3',
    messagingSenderId: '363285191898',
    projectId: 'deardiary-4cfa5',
    authDomain: 'deardiary-4cfa5.firebaseapp.com',
    storageBucket: 'deardiary-4cfa5.appspot.com',
    measurementId: 'G-49MV16C6KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAalTapRpJYkfhlBX_aLwot-ct3UEd5EQU',
    appId: '1:363285191898:android:8efab88f1d6e2db4e499e3',
    messagingSenderId: '363285191898',
    projectId: 'deardiary-4cfa5',
    storageBucket: 'deardiary-4cfa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4dMDwxjul1I65m2wOSXcIN7JIuzw1wLk',
    appId: '1:363285191898:ios:41625e042b4f832ee499e3',
    messagingSenderId: '363285191898',
    projectId: 'deardiary-4cfa5',
    storageBucket: 'deardiary-4cfa5.appspot.com',
    iosBundleId: 'com.example.dearDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4dMDwxjul1I65m2wOSXcIN7JIuzw1wLk',
    appId: '1:363285191898:ios:665bb11bcff4e900e499e3',
    messagingSenderId: '363285191898',
    projectId: 'deardiary-4cfa5',
    storageBucket: 'deardiary-4cfa5.appspot.com',
    iosBundleId: 'com.example.dearDiary.RunnerTests',
  );
}
